// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseBlogWorkDir() {
  return window['go']['main']['App']['ChooseBlogWorkDir']();
}

export function DeleteBlogFile(arg1) {
  return window['go']['main']['App']['DeleteBlogFile'](arg1);
}

export function EnsureWelcomeBlogFile() {
  return window['go']['main']['App']['EnsureWelcomeBlogFile']();
}

export function GetBlogWorkDir() {
  return window['go']['main']['App']['GetBlogWorkDir']();
}

export function GetDefaultBlogWorkDir() {
  return window['go']['main']['App']['GetDefaultBlogWorkDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListBlogMarkdownFiles() {
  return window['go']['main']['App']['ListBlogMarkdownFiles']();
}

export function ReadBlogFile(arg1) {
  return window['go']['main']['App']['ReadBlogFile'](arg1);
}

export function RenameBlogFile(arg1, arg2) {
  return window['go']['main']['App']['RenameBlogFile'](arg1, arg2);
}

export function SetBlogWorkDir(arg1) {
  return window['go']['main']['App']['SetBlogWorkDir'](arg1);
}

export function WriteBlogFile(arg1, arg2) {
  return window['go']['main']['App']['WriteBlogFile'](arg1, arg2);
}
