// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseBlogWorkDir():Promise<string>;

export function DeleteBlogFile(arg1:string):Promise<void>;

export function EnsureWelcomeBlogFile():Promise<void>;

export function GetBlogWorkDir():Promise<string>;

export function GetDefaultBlogWorkDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListBlogMarkdownFiles():Promise<Array<string>>;

export function ReadBlogFile(arg1:string):Promise<string>;

export function RenameBlogFile(arg1:string,arg2:string):Promise<void>;

export function SetBlogWorkDir(arg1:string):Promise<void>;

export function WriteBlogFile(arg1:string,arg2:string):Promise<void>;
